<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "lef_bootstrap_theme"
 *
 * Auto generated by Extension Builder 2015-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Bootstrap Theme',
	'description' => 'Provide advanced bootstrap theme
-basic styles switcher
-lazyload optimized images
-advanced grid system',
	'category' => 'fe',
	'author' => '',
	'author_email' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'themes' => '2.3.2',
			'theme_bootstrap' => '1.0.4',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);